logging:
  level:
    ROOT: INFO

token:
  # That one is from ibft2Genesis.json file. ~90k eth
  # Used as main app key aka God-key
  godKey: c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3

  trxSleep: 2000
  trxAttempts: 20

  # https://docs.web3j.io/command_line_tools/#wallet-tools
  wallet:
    path: wallet/init-wallet.json
    password: top_secret

  # default local address
  netUrl: http://localhost:8545

  contract:
      limit: 5000

  # Network base contracts.
  # fixme: This is done only to make testing easier. In real world they should be probably manually create
  netContracts:
    - name: ERC1820Registry
      # if not specified new will be created. Don't forget to save new address from logs
      address: "0x8cdaf0cd259887258bc13a92c0a6da92698644c0"

    - name: SToken
      # if not specified new will be created. Don't forget to save new address from logs
      address: "0x345ca3e014aaf5dca488057592ee47305d9b3e10"

    - name: STokenExecutor
      # if not specified new will be created. Don't forget to save new address from logs
      address: "0xf25186b5081ff5ce73482ad761db0eb0d25abfbf"

    - name: ScraperTesting
      # if not specified new will be created. Don't forget to save new address from logs
      address: "0xf12b5dd4ead5f743c6baa640b0216200e89b60da"



  # here we can specify users for testing f.i.
  users:
    - privateKey: 5353e554a16dba733f2db6b7924e0e6667758829f177b7f47ced7eba4e03971c
    - privateKey: c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3
